spring:
  application:
    name: hello-spring-cloud-service-admin

  boot:
    admin:
      client:
        url: http://localhost:8084

  #  链路追踪
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/